### ISSUE TITLE
Excon/SageCal code should be fetched from Github

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/spark-archsci-images#2]
When building the images, Excon / SageCal code should be checkout from this repository
https://github.com/nlesc-dirac/sagecal-on-spark

**Comment by SarodYatawatta** [comment]
Do you mean docker images?

**Comment by fdiblen** [comment]
Yes, Docker images.

**Comment by fdiblen** [comment]
solved by 5f8d1920b0b7f265e04ac56744e887f60e9cccec
